sudo: required

language: c

env:
   global:
      - OS_TESTED_CL="clearlinux"
      - OS_TESTED_UBUNTU="ubuntu16.04"
      - OS_TESTED_FEDORA="fedora26"

services:
   - docker

before_install:
   - docker build -t ${OS_TESTED_CL} -f .travis-dockerfiles/Dockerfile.${OS_TESTED_CL} .
   - docker build -t ${OS_TESTED_UBUNTU} -f .travis-dockerfiles/Dockerfile.${OS_TESTED_UBUNTU} .
   - docker build -t ${OS_TESTED_FEDORA} -f .travis-dockerfiles/Dockerfile.${OS_TESTED_FEDORA} .
   - docker images

install: true

script:
   - docker run -v $PWD:/root/acrn ${OS_TESTED_CL} /bin/bash -c "make clean && make"
   - docker run -v $PWD:/root/acrn ${OS_TESTED_UBUNTU} /bin/bash -c "make clean && make"
   - docker run -v $PWD:/root/acrn ${OS_TESTED_FEDORA} /bin/bash -c "make clean && make"
